#!/usr/bin/perl
#
# Copyright (C) 2008 Rackspace US, Inc. <http://www.rackspace.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see http://www.gnu.org/licenses/gpl.txt
#
#
# To enable, link mysql_innodb_buffer_pool to this file. E.g.
#
#    ln -s /usr/share/node/node/plugins/mysql_innodb_buffer_pool /etc/munin/plugins/mysql_innodb_buffer_pool
#
# Revision 1.0  2007/08/03
# Created by Justin Shepherd <jshepher@rackspace.com>
#
# Parameters:
#
#   config
#   autoconf
#
# Configuration variables
#
#   mysqlopts     - Options to pass to mysql
#   mysqladmin    - Override location of mysqladmin
#
#%# family=auto
#%# capabilities=autoconf

use strict;

# Define the mysqladmin paths, and commands
my $MYSQLADMIN = $ENV{mysqladmin} || "mysqladmin";
my $TEST_COMMAND    = "$MYSQLADMIN $ENV{mysqlopts} extended-status";
my $MYSQL_VARIABLES = "$MYSQLADMIN $ENV{mysqlopts} extended-status variables";
# my $warning = $ENV{warning} || "80";
# my $critical = $ENV{critical} || "90";

# Pull in any arguments
my $arg = shift();

# Check to see how the script was called
if ($arg eq 'config') {
    print_graph_information();
    exit();
} elsif ($arg eq 'autoconf') {
    if (test_service()) { print "yes\n"; }
    else { print "no\n"; }
    exit;
} else {
        # Gather the values from mysqladmin
        my $pages_created = poll_variables($MYSQL_VARIABLES,"Innodb_pages_created");
        my $pages_read = poll_variables($MYSQL_VARIABLES,"Innodb_pages_read");
        my $pages_written = poll_variables($MYSQL_VARIABLES,"Innodb_pages_written");

        # Return the values to Munin
        print "pages_created.value $pages_created\n";
        print "pages_read.value $pages_read\n";
        print "pages_written.value $pages_written\n";
}


sub poll_variables {
        my $command = shift;
        my $expression = shift;
        my $ret = 0;
        open(SERVICE, "$command |")
                or die("Coult not execute '$command': $!");
        while (<SERVICE>) {
            my ($field, $value) = (m/(\w+).*?(\d+(?:\.\d+)?)/);
            next unless ($field);
            if ($field eq $expression ) {
                $ret = "$value";
            }
        }
        close(SERVICE);
        return $ret;
}


sub print_graph_information {
print <<EOM;
graph_title InnoDB Buffer Pool Activity
graph_args --base 1000 -l 0
graph_vlabel Pages
graph_category mysql
graph_order pages_created pages_read pages_written
pages_created.label Pages Created
pages_created.draw AREA
pages_created.info The number of pages containing clean data.
pages_read.label Pages Read
pages_read.draw STACK
pages_read.info The number of pages containing dirty data.
pages_written.label Pages Written
pages_written.draw STACK
pages_written.info The number of pages that are busy because they have been allocated for administrative overhead.
EOM
}

sub test_service {
    my $return = 1;
    system ("$MYSQLADMIN --version >/dev/null 2>/dev/null");
    if ($? == 0)
    {
        system ("$TEST_COMMAND >/dev/null 2>/dev/null");
        if ($? == 0)
        {
            if (innodb_enabled()) {
	    	print "yes\n";
            	$return = 0;
	    } else {
		print "no (InnoDB is not enabled)\n";
	    }
        }
        else
        {
            print "no (could not connect to mysql)\n";
        }
    }
    else
    {
        print "no (mysqladmin not found)\n";
    }
    exit $return;
}

sub innodb_enabled {
        my $ret = 0;
        my $out = `mysql $ENV{mysqlopts} -e "show variables like 'have_innodb';" | tail -1`;
        chomp($out);
        my ($tmp, $binlog) = split /\s/,$out,2;
        if ($binlog eq "YES") {
                $ret = 1;
        }
        return $ret;
}

